
# OV7670 FIFO Camera Demo
CONFIG_GPIO=y
CONFIG_I2C=y

# Serial console (required for any UART output on nRF54L15)
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_PRINTK=y

# Logging
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_BACKEND_UART=y

# C++ runtime required by TFLite Micro
CONFIG_CPP=y
CONFIG_STD_CPP17=y

CONFIG_MAIN_STACK_SIZE=4096

# Display
CONFIG_DISPLAY=y
CONFIG_ST7735R=y
CONFIG_MIPI_DBI=y

# TensorFlow Lite Micro
CONFIG_TENSORFLOW_LITE_MICRO=y
CONFIG_TENSORFLOW_LITE_MICRO_CMSIS_NN_KERNELS=y


# Scaling
# Exactly one of these must be enabled
CONFIG_SCALING_1x1=n
CONFIG_SCALING_2x2=y
CONFIG_SCALING_3x3=n
CONFIG_SCALING_4x4=n
# /Scaling
